name: helloworld
description: gRPC test for dart

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  async: ^2.2.0
  grpc: ^2.1.3
  protobuf: ^1.0.0
  

dev_dependencies:
  test: ^1.6.4
